spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum;NON_KEYWORDS=user
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true